#error (33:1): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Given Admin user is logged into Content Editor application'
#error (34:2): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'When Admin opens following item'
#error (35:2): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got '| Item Path                                                    | Field Name    |'
#error (36:2): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got '| /sitecore/content/Habitat/Home/About Habitat/Getting Started | Meta Keywords |'
#error (37:2): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'And Admin assign <sitecore> keyword'
#error (38:2): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'And Admin assign <habitat> keyword'
#error (39:2): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'And Admin saves changes on the item'
#error (40:2): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Then page HTML contains following tag'
#error (41:2): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got '|Tag                                                |'
#error (42:2): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got '|<meta name="keywords" content="sitecore, habitat"> |'
#error (43:0): unexpected end of file, expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty