---
ID: 8d8edb18-b641-4277-bad3-9c6cf89f9fe3
Parent: 8a80477e-7cb4-4cee-a035-b48ac118abe8
Template: 8ee208f9-a6a6-41e2-88a0-c188737a178c
Path: /sitecore/content/Habitat/Home/Modules/Project
SharedFields:
- ID: ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e
  # __Sortorder
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 1b483e91-d8c4-4d19-ba03-462074b55936
      # NavigationTitle
      Value: Project
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150925T003918Z
    - ID: 9492e0bb-9df9-46e7-8188-ec795c4ade44
      # Image
      Value: "<image mediaid=\"{D295ABFF-4BE5-4C08-A8E6-ED8DC49E927B}\" />"
    - ID: ac3fd4db-8266-476d-9635-67814d91e901
      # Summary
      Value: The project bind the solution together. There are typically two project modules: Website, containing the page layouts and page types, and Design, which contains the visual design of the solution.<br>A solution could have multiple project websites where each website can have their own page types, layouts and designs.<br>
    - ID: c30a013f-3cc8-4961-9837-1c483277084a
      # Title
      Value: Project
    - ID: ca0479ce-0bfe-4522-83de-ba688b380a78
      # BrowserTitle
      Value: Project
