---
ID: "a71c3a41-08fa-4da0-909b-c4c52f531cde"
Parent: "0fccfe4f-b087-498f-bd26-5cdffc522c9a"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Feature/Multisite/_SiteConfiguration/Site
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151209T153818Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
