// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Sitecore.Feature.Specflow
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "UI")]
    public partial class Person_EmployeeListFeature : Xunit.IClassFixture<Person_EmployeeListFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Person_Employee List.feature"
#line hidden
        
        public Person_EmployeeListFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Person_Employee List", null, ProgrammingLanguage.CSharp, new string[] {
                        "UI"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(Person_EmployeeListFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Person_Employee List")]
        [Xunit.TraitAttribute("Description", "Person_Employee List_UC1_Default search query")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Person_EmployeeList_UC1_DefaultSearchQuery()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Person_Employee List_UC1_Default search query", new string[] {
                        "Ready"});
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("Habitat website is opened on Main Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.When("Actor navigates to Employees-List page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Person"});
            table1.AddRow(new string[] {
                        "JOHN HOWARD"});
            table1.AddRow(new string[] {
                        "JOHN DOE"});
#line 9
 testRunner.Then("Only following persons are shown", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Person_Employee List")]
        [Xunit.TraitAttribute("Description", "Person_Employee List_UC2_Custom search query_text type was defined")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Person_EmployeeList_UC2_CustomSearchQuery_TextTypeWasDefined()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Person_Employee List_UC2_Custom search query_text type was defined", new string[] {
                        "Ready"});
#line 16
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "ItemPath",
                        "ControlId",
                        "Type",
                        "Value"});
            table2.AddRow(new string[] {
                        "/sitecore/content/Habitat/Home/Modules/Feature/Person/Employees List",
                        "{DC19892A-B345-4EFE-AAA2-6E27A801A733}",
                        "DataSource",
                        "text:CEO"});
#line 17
 testRunner.Given("Control properties were defined for item", ((string)(null)), table2, "Given ");
#line 20
 testRunner.And("Habitat website is opened on Main Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.When("Actor navigates to Employees-List page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Person"});
            table3.AddRow(new string[] {
                        "JOHN DOE"});
#line 22
 testRunner.Then("Only following persons are shown", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Person_Employee List")]
        [Xunit.TraitAttribute("Description", "Person_Employee List_UC3_Custom search query_field type was defined")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Person_EmployeeList_UC3_CustomSearchQuery_FieldTypeWasDefined()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Person_Employee List_UC3_Custom search query_field type was defined", new string[] {
                        "Ready"});
#line 27
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Item path",
                        "Control ID",
                        "Type",
                        "Value"});
            table4.AddRow(new string[] {
                        "/sitecore/content/Habitat/Home/Modules/Feature/Person/Employees List",
                        "{DC19892A-B345-4EFE-AAA2-6E27A801A733}",
                        "DataSource",
                        "template:{467c2144-4454-4518-b1de-e31b4cbbff33}"});
#line 28
 testRunner.Given("Control properties were defined for item", ((string)(null)), table4, "Given ");
#line 31
 testRunner.And("Actor navigates to Employees-List page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Person"});
            table5.AddRow(new string[] {
                        "JOHN HOWARD"});
            table5.AddRow(new string[] {
                        "JOHN DOE"});
#line 32
 testRunner.Then("Only following persons are shown", ((string)(null)), table5, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Person_Employee List")]
        [Xunit.TraitAttribute("Description", "Person_Employee List_UC4_Custom search query_field and text types were defined")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Person_EmployeeList_UC4_CustomSearchQuery_FieldAndTextTypesWereDefined()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Person_Employee List_UC4_Custom search query_field and text types were defined", new string[] {
                        "Ready"});
#line 39
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Item path",
                        "Control ID",
                        "Type",
                        "Value"});
            table6.AddRow(new string[] {
                        "/sitecore/content/Habitat/Home/Modules/Feature/Person/Employees List",
                        "{DC19892A-B345-4EFE-AAA2-6E27A801A733}",
                        "DataSource",
                        "text:John;template:{467c2144-4454-4518-b1de-e31b4cbbff33}"});
#line 40
 testRunner.Given("Control properties were defined for item", ((string)(null)), table6, "Given ");
#line 43
 testRunner.And("Actor navigates to Employees-List page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Person"});
            table7.AddRow(new string[] {
                        "JOHN HOWARD"});
            table7.AddRow(new string[] {
                        "JOHN DOE"});
#line 44
 testRunner.Then("Only following persons are shown", ((string)(null)), table7, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Person_Employee List")]
        [Xunit.TraitAttribute("Description", "Person_Employee List_UC5_Custom search query_field and text types were defined_In" +
            "clude criteria logic")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Person_EmployeeList_UC5_CustomSearchQuery_FieldAndTextTypesWereDefined_IncludeCriteriaLogic()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Person_Employee List_UC5_Custom search query_field and text types were defined_In" +
                    "clude criteria logic", new string[] {
                        "Ready"});
#line 51
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Item path",
                        "Control ID",
                        "Type",
                        "Value"});
            table8.AddRow(new string[] {
                        "/sitecore/content/Habitat/Home/Modules/Feature/Person/Employees List",
                        "{DC19892A-B345-4EFE-AAA2-6E27A801A733}",
                        "DataSource",
                        "text:John;+template:{467c2144-4454-4518-b1de-e31b4cbbff33}"});
#line 52
 testRunner.Given("Control properties were defined for item", ((string)(null)), table8, "Given ");
#line 55
 testRunner.And("Actor navigates to Employees-List page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Person"});
            table9.AddRow(new string[] {
                        "JOHN HOWARD"});
            table9.AddRow(new string[] {
                        "JOHN DOE"});
#line 56
 testRunner.Then("Only following persons are shown", ((string)(null)), table9, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Person_Employee List")]
        [Xunit.TraitAttribute("Description", "Person_Employee List_UC6_Custom search query_Exclude criteria logic")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Person_EmployeeList_UC6_CustomSearchQuery_ExcludeCriteriaLogic()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Person_Employee List_UC6_Custom search query_Exclude criteria logic", new string[] {
                        "Ready"});
#line 62
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Item path",
                        "Control ID",
                        "Type",
                        "Value"});
            table10.AddRow(new string[] {
                        "/sitecore/content/Habitat/Home/Modules/Feature/Person/Employees List",
                        "{DC19892A-B345-4EFE-AAA2-6E27A801A733}",
                        "DataSource",
                        "text:John;-text:CEO"});
#line 63
 testRunner.Given("Control properties were defined for item", ((string)(null)), table10, "Given ");
#line 66
 testRunner.And("Actor navigates to Employees-List page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Person"});
            table11.AddRow(new string[] {
                        "JOHN HOWARD"});
#line 67
 testRunner.Then("Only following persons are shown", ((string)(null)), table11, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Person_Employee List")]
        [Xunit.TraitAttribute("Description", "Person_Employee List_UC7_Custom search query_New version of the item is defined")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Person_EmployeeList_UC7_CustomSearchQuery_NewVersionOfTheItemIsDefined()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Person_Employee List_UC7_Custom search query_New version of the item is defined", new string[] {
                        "Ready"});
#line 73
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Item path",
                        "Control ID",
                        "Type",
                        "Value"});
            table12.AddRow(new string[] {
                        "/sitecore/content/Habitat/Home/Modules/Feature/Person/Employees List",
                        "{DC19892A-B345-4EFE-AAA2-6E27A801A733}",
                        "DataSource",
                        "text:John;template:{467c2144-4454-4518-b1de-e31b4cbbff33}"});
#line 74
 testRunner.Given("Control properties were defined for item", ((string)(null)), table12, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Item path",
                        "Language"});
            table13.AddRow(new string[] {
                        "/sitecore/content/Habitat/Home/Modules/Feature/Person/Employees List/John Doe",
                        "de"});
#line 77
 testRunner.And("New item version was added", ((string)(null)), table13, "And ");
#line 80
 testRunner.When("Actor navigates to Employees-List page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Person"});
            table14.AddRow(new string[] {
                        "JOHN HOWARD"});
            table14.AddRow(new string[] {
                        "JOHN DOE"});
#line 81
 testRunner.Then("Only following persons are shown", ((string)(null)), table14, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Person_Employee List")]
        [Xunit.TraitAttribute("Description", "Person_Employee List_UC8_Custom search query_New language of the item is defined")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Person_EmployeeList_UC8_CustomSearchQuery_NewLanguageOfTheItemIsDefined()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Person_Employee List_UC8_Custom search query_New language of the item is defined", new string[] {
                        "Ready"});
#line 88
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Item path",
                        "Control ID",
                        "Type",
                        "Value"});
            table15.AddRow(new string[] {
                        "/sitecore/content/Habitat/Home/Modules/Feature/Person/Employees List",
                        "{DC19892A-B345-4EFE-AAA2-6E27A801A733}",
                        "DataSource",
                        "text:John;template:{467c2144-4454-4518-b1de-e31b4cbbff33}"});
#line 89
 testRunner.Given("Control properties were defined for item", ((string)(null)), table15, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Item path",
                        "Language"});
            table16.AddRow(new string[] {
                        "/sitecore/content/Habitat/Home/Modules/Feature/Person/Employees List",
                        "en"});
#line 92
 testRunner.And("New item version was added", ((string)(null)), table16, "And ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "ItemPath",
                        "FieldName",
                        "FieldValue"});
            table17.AddRow(new string[] {
                        "/sitecore/content/Habitat/Home/Modules/Feature/Person/Employees List/John Howard",
                        "Name",
                        "John Howard"});
#line 95
 testRunner.And("Value set to item field", ((string)(null)), table17, "And ");
#line 98
 testRunner.When("Actor navigates to Employees-List page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Person"});
            table18.AddRow(new string[] {
                        "JOHN HOWARD"});
            table18.AddRow(new string[] {
                        "JOHN DOE"});
#line 99
 testRunner.Then("Only following persons are shown", ((string)(null)), table18, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Person_Employee List")]
        [Xunit.TraitAttribute("Description", "Person_Employee List_UC9_Default search query with custom Search Result Limit")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Person_EmployeeList_UC9_DefaultSearchQueryWithCustomSearchResultLimit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Person_Employee List_UC9_Default search query with custom Search Result Limit", new string[] {
                        "Ready"});
#line 106
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Item path",
                        "Control ID",
                        "Type",
                        "Value"});
            table19.AddRow(new string[] {
                        "/sitecore/content/Habitat/Home/Modules/Feature/Person/Employees List",
                        "{DC19892A-B345-4EFE-AAA2-6E27A801A733}",
                        "DataSource",
                        "text:CEO"});
#line 107
 testRunner.Given("Control properties were defined for item", ((string)(null)), table19, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Item path",
                        "Control ID",
                        "Type",
                        "Value"});
            table20.AddRow(new string[] {
                        "/sitecore/content/Habitat/Home/Modules/Feature/Person/Employees List",
                        "{DC19892A-B345-4EFE-AAA2-6E27A801A733}",
                        "SearchResultLimit",
                        "1"});
#line 110
 testRunner.And("Control properties were defined for item", ((string)(null)), table20, "And ");
#line 113
 testRunner.When("Actor navigates to Employees-List page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Person"});
            table21.AddRow(new string[] {
                        "JOHN DOE"});
#line 114
 testRunner.Then("Only following persons are shown", ((string)(null)), table21, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Person_Employee List")]
        [Xunit.TraitAttribute("Description", "Person_Employee List_UC10_Default search query with null Search Result Limit")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Person_EmployeeList_UC10_DefaultSearchQueryWithNullSearchResultLimit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Person_Employee List_UC10_Default search query with null Search Result Limit", new string[] {
                        "Ready"});
#line 120
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Item path",
                        "Control ID",
                        "Type",
                        "Value"});
            table22.AddRow(new string[] {
                        "/sitecore/content/Habitat/Home/Modules/Feature/Person/Employees List",
                        "{DC19892A-B345-4EFE-AAA2-6E27A801A733}",
                        "DataSource",
                        "template:{467c2144-4454-4518-b1de-e31b4cbbff33}"});
#line 121
 testRunner.Given("Control properties were defined for item", ((string)(null)), table22, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Item path",
                        "Control ID",
                        "Type",
                        "Value"});
            table23.AddRow(new string[] {
                        "/sitecore/content/Habitat/Home/Modules/Feature/Person/Employees List",
                        "{DC19892A-B345-4EFE-AAA2-6E27A801A733}",
                        "SearchResultLimit",
                        ""});
#line 124
 testRunner.And("Control properties were defined for item", ((string)(null)), table23, "And ");
#line 127
 testRunner.When("Actor navigates to Employees-List page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Person"});
            table24.AddRow(new string[] {
                        "JOHN HOWARD"});
            table24.AddRow(new string[] {
                        "JOHN DOE"});
#line 128
 testRunner.Then("Only following persons are shown", ((string)(null)), table24, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                Person_EmployeeListFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                Person_EmployeeListFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
