// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Habitat.Accounts.Specflow
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SaveUserDetailsInXDBFeature : Xunit.IUseFixture<SaveUserDetailsInXDBFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Save user details in xDB.feature"
#line hidden
        
        public SaveUserDetailsInXDBFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Save user details in xDB", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(SaveUserDetailsInXDBFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Save user details in xDB")]
        [Xunit.TraitAttribute("Description", "Account_Save user details in xDB_UC1_Save full info")]
        public virtual void Account_SaveUserDetailsInXDB_UC1_SaveFullInfo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Save user details in xDB_UC1_Save full info", new string[] {
                        "NeedImplementation"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "ConfirmPassword"});
            table1.AddRow(new string[] {
                        "kov@sitecore.net",
                        "k",
                        "k"});
#line 6
 testRunner.Given("User with following data is registered in Habitat", ((string)(null)), table1, "Given ");
#line 9
 testRunner.And("Habitat website is opened on Edit Profile page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number"});
            table2.AddRow(new string[] {
                        "Maximov",
                        "Stas",
                        "+38(067)8888888"});
#line 10
 testRunner.And("User inputs data in to the fields", ((string)(null)), table2, "And ");
#line 13
 testRunner.And("User selects <Skiing> from Interests drop-down list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.When("User clicks Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
 testRunner.And("User opens MongoDB", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number",
                        "Interests"});
            table3.AddRow(new string[] {
                        "Teltov",
                        "Konstantin",
                        "+38(067)3333333",
                        "Swiming"});
#line 16
 testRunner.And("Following info presents in MongoDB", ((string)(null)), table3, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Save user details in xDB")]
        [Xunit.TraitAttribute("Description", "Account_Save user details in xDB_UC2_Update full user info")]
        public virtual void Account_SaveUserDetailsInXDB_UC2_UpdateFullUserInfo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Save user details in xDB_UC2_Update full user info", new string[] {
                        "NeedImplementation"});
#line 22
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number",
                        "Interests"});
            table4.AddRow(new string[] {
                        "Teltov",
                        "Konstantin",
                        "+38(067)3333333",
                        "Swiming"});
#line 23
 testRunner.Given("Habitat user was created and updated with following info", ((string)(null)), table4, "Given ");
#line 26
 testRunner.And("Habitat website is opened on Edit Profile page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number"});
            table5.AddRow(new string[] {
                        "Maximov",
                        "Stas",
                        "+38(067)8888888"});
#line 27
 testRunner.When("User inputs data in to the fields", ((string)(null)), table5, "When ");
#line 30
 testRunner.And("User selects <Skiing> from Interests drop-down list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.And("User clicks Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.And("User opens MongoDB", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number",
                        "Interests"});
            table6.AddRow(new string[] {
                        "Maximov",
                        "Stas",
                        "+38(067)8888888",
                        "Skiing"});
#line 33
 testRunner.And("Following info presents in MongoDB", ((string)(null)), table6, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Save user details in xDB")]
        [Xunit.TraitAttribute("Description", "Account_Save user details in xDB_UC3_Save only one of the name fields")]
        public virtual void Account_SaveUserDetailsInXDB_UC3_SaveOnlyOneOfTheNameFields()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Save user details in xDB_UC3_Save only one of the name fields", new string[] {
                        "NeedImplementation"});
#line 39
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "ConfirmPassword"});
            table7.AddRow(new string[] {
                        "kov@sitecore.net",
                        "k",
                        "k"});
#line 40
 testRunner.Given("User with following data is registered in Habitat", ((string)(null)), table7, "Given ");
#line 43
 testRunner.And("Habitat website is opened on Edit Profile page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name"});
            table8.AddRow(new string[] {
                        "Maximov"});
#line 44
 testRunner.When("User inputs data in to the fields", ((string)(null)), table8, "When ");
#line 47
 testRunner.And("User clicks Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.And("User opens MongoDB", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number",
                        "Interests"});
            table9.AddRow(new string[] {
                        "Maximov",
                        "empty",
                        "empty",
                        "empty"});
#line 49
 testRunner.And("Following info presents in MongoDB", ((string)(null)), table9, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Save user details in xDB")]
        [Xunit.TraitAttribute("Description", "Account_Save user details in xDB_UC4_Save only phone number")]
        public virtual void Account_SaveUserDetailsInXDB_UC4_SaveOnlyPhoneNumber()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Save user details in xDB_UC4_Save only phone number", new string[] {
                        "NeedImplementation"});
#line 55
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "ConfirmPassword"});
            table10.AddRow(new string[] {
                        "kov@sitecore.net",
                        "k",
                        "k"});
#line 56
 testRunner.Given("User with following data is registered in Habitat", ((string)(null)), table10, "Given ");
#line 59
 testRunner.And("Habitat website is opened on Edit Profile page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number"});
            table11.AddRow(new string[] {
                        "+38(067)8888888"});
#line 60
 testRunner.When("User inputs data in to the fields", ((string)(null)), table11, "When ");
#line 63
 testRunner.And("User clicks Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
 testRunner.And("User opens MongoDB", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number",
                        "Interests"});
            table12.AddRow(new string[] {
                        "empty",
                        "empty",
                        "+38(067)8888888",
                        "empty"});
#line 65
 testRunner.And("Following info presents in MongoDB", ((string)(null)), table12, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Save user details in xDB")]
        [Xunit.TraitAttribute("Description", "Account_Save user details in xDB_UC5_Save only Interests")]
        public virtual void Account_SaveUserDetailsInXDB_UC5_SaveOnlyInterests()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Save user details in xDB_UC5_Save only Interests", new string[] {
                        "NeedImplementation"});
#line 72
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "ConfirmPassword"});
            table13.AddRow(new string[] {
                        "kov@sitecore.net",
                        "k",
                        "k"});
#line 73
 testRunner.Given("User with following data is registered in Habitat", ((string)(null)), table13, "Given ");
#line 76
 testRunner.And("Habitat website is opened on Edit Profile page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.When("User selects <Skiing> from Interests drop-down list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 78
 testRunner.And("User clicks Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
 testRunner.And("User opens MongoDB", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number",
                        "Interests"});
            table14.AddRow(new string[] {
                        "empty",
                        "empty",
                        "empty",
                        "Skiing"});
#line 80
 testRunner.And("Following info presents in MongoDB", ((string)(null)), table14, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Save user details in xDB")]
        [Xunit.TraitAttribute("Description", "Account_Save user details in xDB_UC6_Update only one of the name fields")]
        public virtual void Account_SaveUserDetailsInXDB_UC6_UpdateOnlyOneOfTheNameFields()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Save user details in xDB_UC6_Update only one of the name fields", new string[] {
                        "NeedImplementation"});
#line 87
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number",
                        "Interests"});
            table15.AddRow(new string[] {
                        "Teltov",
                        "Konstantin",
                        "+38(067)3333333",
                        "Swiming"});
#line 88
 testRunner.Given("Habitat user was created and updated with following info", ((string)(null)), table15, "Given ");
#line 91
 testRunner.And("Habitat website is opened on Edit Profile page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name"});
            table16.AddRow(new string[] {
                        "Maximov"});
#line 92
 testRunner.When("User inputs data in to the fields", ((string)(null)), table16, "When ");
#line 95
 testRunner.And("User clicks Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 96
 testRunner.And("User opens MongoDB", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number",
                        "Interests"});
            table17.AddRow(new string[] {
                        "Maximov",
                        "Konstantin",
                        "+38(067)3333333",
                        "Swiming"});
#line 97
 testRunner.And("Following info presents in MongoDB", ((string)(null)), table17, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Save user details in xDB")]
        [Xunit.TraitAttribute("Description", "Account_Save user details in xDB_UC7_Update only phone number")]
        public virtual void Account_SaveUserDetailsInXDB_UC7_UpdateOnlyPhoneNumber()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Save user details in xDB_UC7_Update only phone number", new string[] {
                        "NeedImplementation"});
#line 103
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number",
                        "Interests"});
            table18.AddRow(new string[] {
                        "Teltov",
                        "Konstantin",
                        "+38(067)3333333",
                        "Swiming"});
#line 104
 testRunner.Given("Habitat user was created and updated with following info", ((string)(null)), table18, "Given ");
#line 107
 testRunner.And("Habitat website is opened on Edit Profile page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number"});
            table19.AddRow(new string[] {
                        "+38(067)8888888"});
#line 108
 testRunner.When("User inputs data in to the fields", ((string)(null)), table19, "When ");
#line 111
 testRunner.And("User clicks Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 112
 testRunner.And("User opens MongoDB", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number",
                        "Interests"});
            table20.AddRow(new string[] {
                        "Teltov",
                        "Konstantin",
                        "+38(067)8888888",
                        "Swiming"});
#line 113
 testRunner.And("Following info presents in MongoDB", ((string)(null)), table20, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Save user details in xDB")]
        [Xunit.TraitAttribute("Description", "Account_Save user details in xDB_UC8_Update only only Interests")]
        public virtual void Account_SaveUserDetailsInXDB_UC8_UpdateOnlyOnlyInterests()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Save user details in xDB_UC8_Update only only Interests", new string[] {
                        "NeedImplementation"});
#line 118
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number",
                        "Interests"});
            table21.AddRow(new string[] {
                        "Teltov",
                        "Konstantin",
                        "+38(067)3333333",
                        "Swiming"});
#line 119
 testRunner.Given("Habitat user was created and updated with following info", ((string)(null)), table21, "Given ");
#line 122
 testRunner.And("Habitat website is opened on Edit Profile page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 123
 testRunner.When("User selects <Skiing> from Interests drop-down list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 124
 testRunner.And("User clicks Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 125
 testRunner.And("User opens MongoDB", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number",
                        "Interests"});
            table22.AddRow(new string[] {
                        "Teltov",
                        "Konstantin",
                        "+38(067)3333333",
                        "Skiing"});
#line 126
 testRunner.And("Following info presents in MongoDB", ((string)(null)), table22, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SaveUserDetailsInXDBFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SaveUserDetailsInXDBFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
