---
ID: bccfebea-dccb-48fe-9570-6503829ec03f
Parent: df639de8-c9e7-4b18-967e-b1a14a8ff221
Template: ab86861a-6030-46c5-b394-e8f99e8b87db
Path: /sitecore/templates/Foundation/Multisite/_SiteSettings
DB: master
SharedFields:
- ID: 12c33f3f-86c5-43a5-aeb4-5598cec45116
  Hint: __Base template
  Type: tree list
  Value: {1930BBEB-7805-471A-A3BE-4858AC7CF696}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160105T034901Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\admin
