---
ID: "638579ab-e35e-4ad5-8306-fa6b1768c6bf"
Parent: "9671e92a-4ad3-46df-aff1-1542fd3d5bd9"
Template: "9671e92a-4ad3-46df-aff1-1542fd3d5bd9"
Path: /sitecore/templates/Project/Common/Content Types/Employee/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161202T033448Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
