// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

#region Designer generated code


#pragma warning disable

namespace Habitat.Accounts.Specflow
{
  using TechTalk.SpecFlow;

  [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
  [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  public partial class ContactIdentificationFeature : Xunit.IUseFixture<ContactIdentificationFeature.FixtureData>, System.IDisposable
  {
    private static TechTalk.SpecFlow.ITestRunner testRunner;

#line 1 "Contact Identification.feature"
#line hidden

    public ContactIdentificationFeature()
    {
      this.TestInitialize();
    }

    public static void FeatureSetup()
    {
      testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
      var featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Contact Identification", "\nAs a sales person \r\nI want to show that Sitecore tracks the indentifiction of a " +
                                                                                                                                   "visitor \r\nso that I can show the we know a person across visits", ProgrammingLanguage.CSharp, ((string[])(null)));
      testRunner.OnFeatureStart(featureInfo);
    }

    public static void FeatureTearDown()
    {
      testRunner.OnFeatureEnd();
      testRunner = null;
    }

    public virtual void TestInitialize()
    {
    }

    public virtual void ScenarioTearDown()
    {
      testRunner.OnScenarioEnd();
    }

    public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
    {
      testRunner.OnScenarioStart(scenarioInfo);
    }

    public virtual void ScenarioCleanup()
    {
      testRunner.CollectScenarioErrors();
    }

    public virtual void SetFixture(ContactIdentificationFeature.FixtureData fixtureData)
    {
    }

    void System.IDisposable.Dispose()
    {
      this.ScenarioTearDown();
    }

    [Xunit.FactAttribute()]
    [Xunit.TraitAttribute("FeatureTitle", "Contact Identification")]
    [Xunit.TraitAttribute("Description", "Accounts_Contact Identification_UC1_Identification is shown in the demo contact p" +
                                         "anel")]
    public virtual void Accounts_ContactIdentification_UC1_IdentificationIsShownInTheDemoContactPanel()
    {
      var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Accounts_Contact Identification_UC1_Identification is shown in the demo contact p" +
                                                            "anel", new string[]
                                                            {
                                                              "NeedImplementation"
                                                            });
#line 8
      this.ScenarioSetup(scenarioInfo);
#line 9
      testRunner.Given("Habitat website is opened on Main Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
      testRunner.When("Actor clicks on <Info-sign> in the right down corner", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
      testRunner.And("Actor expands Identification section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
      testRunner.Then("Contact ID term with it\'s ID presents", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 13
      testRunner.And("Identifier is empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
      testRunner.And("Identification status is <None>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
      var table1 = new TechTalk.SpecFlow.Table(new string[]
      {
        "Number of visits"
      });
      table1.AddRow(new string[]
      {
        "1"
      });
#line 15
      testRunner.And("System shows following info on Contact panel title", ((string)(null)), table1, "And ");
#line hidden
      this.ScenarioCleanup();
    }

    [Xunit.FactAttribute()]
    [Xunit.TraitAttribute("FeatureTitle", "Contact Identification")]
    [Xunit.TraitAttribute("Description", "Accounts_Contact Identification_UC2_Identification is shown in the demo contact p" +
                                         "anel for just registered user")]
    public virtual void Accounts_ContactIdentification_UC2_IdentificationIsShownInTheDemoContactPanelForJustRegisteredUser()
    {
      var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Accounts_Contact Identification_UC2_Identification is shown in the demo contact p" +
                                                            "anel for just registered user", new string[]
                                                            {
                                                              "NeedImplementation"
                                                            });
#line 21
      this.ScenarioSetup(scenarioInfo);
#line 22
      testRunner.Given("Habitat website is opened on Register page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
      var table2 = new TechTalk.SpecFlow.Table(new string[]
      {
        "Email",
        "Password",
        "ConfirmPassword"
      });
      table2.AddRow(new string[]
      {
        "kov@sitecore.net",
        "k",
        "k"
      });
#line 23
      testRunner.And("Actor entered following data in to the register fields", ((string)(null)), table2, "And ");
#line 26
      testRunner.And("Actor clicked Register button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
      testRunner.When("User clicks on <Info-sign> in the right down corner", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 28
      testRunner.And("User expands Identification section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
      testRunner.Then("Contact ID term with it\'s ID presents", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 30
      testRunner.And("Identifier is <extranet\\kov@sitecore.net>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
      testRunner.And("Identification status is <Known>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
      var table3 = new TechTalk.SpecFlow.Table(new string[]
      {
        "Number of visits"
      });
      table3.AddRow(new string[]
      {
        "2"
      });
#line 32
      testRunner.And("System shows following info on Contact panel title", ((string)(null)), table3, "And ");
#line hidden
      this.ScenarioCleanup();
    }

    [Xunit.FactAttribute()]
    [Xunit.TraitAttribute("FeatureTitle", "Contact Identification")]
    [Xunit.TraitAttribute("Description", "Accounts_Contact Identification_UC3_Identification is shown in the demo contact p" +
                                         "anel for logged in user")]
    public virtual void Accounts_ContactIdentification_UC3_IdentificationIsShownInTheDemoContactPanelForLoggedInUser()
    {
      var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Accounts_Contact Identification_UC3_Identification is shown in the demo contact p" +
                                                            "anel for logged in user", new string[]
                                                            {
                                                              "NeedImplementation"
                                                            });
#line 38
      this.ScenarioSetup(scenarioInfo);
#line hidden
      var table4 = new TechTalk.SpecFlow.Table(new string[]
      {
        "Email",
        "Password",
        "ConfirmPassword"
      });
      table4.AddRow(new string[]
      {
        "kov@sitecore.net",
        "k",
        "k"
      });
#line 39
      testRunner.Given("User is registered in Habitat and logged out", ((string)(null)), table4, "Given ");
#line 42
      testRunner.And("Habitat website is opened on Forgot Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
      var table5 = new TechTalk.SpecFlow.Table(new string[]
      {
        "Email",
        "Password"
      });
      table5.AddRow(new string[]
      {
        "kov@sitecore.net",
        "k"
      });
#line 43
      testRunner.When("Actor enteres following data into Login page fields", ((string)(null)), table5, "When ");
#line 46
      testRunner.And("Actor clicks Login button on Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
      testRunner.And("User clicks on <Info-sign> in the right down corner", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
      testRunner.And("User expands Identification section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
      testRunner.Then("Contact ID term with it\'s ID presents", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 50
      testRunner.And("Identifier is <extranet\\kov@sitecore.net>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
      testRunner.And("Identification status is <Known>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
      var table6 = new TechTalk.SpecFlow.Table(new string[]
      {
        "Number of visits"
      });
      table6.AddRow(new string[]
      {
        "3"
      });
#line 52
      testRunner.And("System shows following info on Contact panel title", ((string)(null)), table6, "And ");
#line hidden
      this.ScenarioCleanup();
    }

    [Xunit.FactAttribute()]
    [Xunit.TraitAttribute("FeatureTitle", "Contact Identification")]
    [Xunit.TraitAttribute("Description", "Accounts_Contact Identification_UC4_Start a new session")]
    public virtual void Accounts_ContactIdentification_UC4_StartANewSession()
    {
      var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Accounts_Contact Identification_UC4_Start a new session", new string[]
      {
        "NeedImplementation"
      });
#line 58
      this.ScenarioSetup(scenarioInfo);
#line hidden
      var table7 = new TechTalk.SpecFlow.Table(new string[]
      {
        "Email",
        "Password",
        "ConfirmPassword"
      });
      table7.AddRow(new string[]
      {
        "kov@sitecore.net",
        "k",
        "k"
      });
#line 59
      testRunner.Given("User is registered in Habitat and logged in", ((string)(null)), table7, "Given ");
#line 62
      testRunner.And("Identification section in the demo contact panel is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
      testRunner.And("Contact ID term with it\'s ID presented", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
      testRunner.And("Identifier was <extranet\\kov@sitecore.net>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
      testRunner.And("Identification status was <Known>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
      var table8 = new TechTalk.SpecFlow.Table(new string[]
      {
        "Number of visits"
      });
      table8.AddRow(new string[]
      {
        "2"
      });
#line 66
      testRunner.And("System shown following info on Contact panel title", ((string)(null)), table8, "And ");
#line 69
      testRunner.When("User clicks END VISIT button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 70
      testRunner.And("User clicks on <Info-sign> in the right down corner", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
      testRunner.And("User expands Identification section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 72
      testRunner.Then("System shows the same Contact ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
      var table9 = new TechTalk.SpecFlow.Table(new string[]
      {
        "Number of visits"
      });
      table9.AddRow(new string[]
      {
        "3"
      });
#line 73
      testRunner.And("System shows following info on Contact panel title", ((string)(null)), table9, "And ");
#line hidden
      this.ScenarioCleanup();
    }

    [Xunit.FactAttribute()]
    [Xunit.TraitAttribute("FeatureTitle", "Contact Identification")]
    [Xunit.TraitAttribute("Description", "Accounts_Contact Identification_UC5_Clear browser cookies")]
    public virtual void Accounts_ContactIdentification_UC5_ClearBrowserCookies()
    {
      var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Accounts_Contact Identification_UC5_Clear browser cookies", new string[]
      {
        "NeedImplementation"
      });
#line 79
      this.ScenarioSetup(scenarioInfo);
#line hidden
      var table10 = new TechTalk.SpecFlow.Table(new string[]
      {
        "Email",
        "Password",
        "ConfirmPassword"
      });
      table10.AddRow(new string[]
      {
        "kov@sitecore.net",
        "k",
        "k"
      });
#line 80
      testRunner.Given("User is registered in Habitat and logged in", ((string)(null)), table10, "Given ");
#line 83
      testRunner.And("Identification section in the demo contact panel is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 84
      testRunner.And("Contact ID term with it\'s ID presented", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 85
      testRunner.And("Identifier was <extranet\\kov@sitecore.net>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 86
      testRunner.And("Identification status was <Known>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
      var table11 = new TechTalk.SpecFlow.Table(new string[]
      {
        "Number of visits"
      });
      table11.AddRow(new string[]
      {
        "2"
      });
#line 87
      testRunner.And("System shown following info on Contact panel title", ((string)(null)), table11, "And ");
#line 90
      testRunner.When("clear browser cookies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
      var table12 = new TechTalk.SpecFlow.Table(new string[]
      {
        "Email",
        "Password"
      });
      table12.AddRow(new string[]
      {
        "kov@sitecore.net",
        "k"
      });
#line 91
      testRunner.And("login with following user", ((string)(null)), table12, "And ");
#line 94
      testRunner.And("User clicks on <Info-sign> in the right down corner", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 95
      testRunner.And("User expands Identification section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 96
      testRunner.Then("System shows the same Contact ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 97
      testRunner.And("Identifier is <extranet\\kov@sitecore.net>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 98
      testRunner.And("Identification status is <Known>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
      var table13 = new TechTalk.SpecFlow.Table(new string[]
      {
        "Number of visits"
      });
      table13.AddRow(new string[]
      {
        "3"
      });
#line 99
      testRunner.And("System shows following info on Contact panel title", ((string)(null)), table13, "And ");
#line hidden
      this.ScenarioCleanup();
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FixtureData : System.IDisposable
    {
      public FixtureData()
      {
        FeatureSetup();
      }

      void System.IDisposable.Dispose()
      {
        FeatureTearDown();
      }
    }
  }
}

#pragma warning restore

#endregion