//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Foundation.Multisite.Models.Foundation.Multisite {
    
    
    /// <summary>Represents the /sitecore/templates/Foundation/Multisite/Datasource Configuration template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{C82DC5FF-09EF-4403-96D3-3CAF377B8C5B}", "S/C5xQrXGioJOKHEAq7sey52WX0=", "Sitecore.Foundation.Multisite")]
    public partial interface IDatasourceConfigurationItem : global::Sitecore.Foundation.Multisite.Models.Foundation.Multisite.I_SiteSettingsItem {
        
        /// <summary>Represents the DatasourceLocation field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("datasourcelocation")]
        Synthesis.FieldTypes.Interfaces.ITextField DatasourceLocation {
            get;
        }
        
        /// <summary>Represents the DatasourceTemplate field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("datasourcetemplate")]
        Synthesis.FieldTypes.Interfaces.IPathItemReferenceField DatasourceTemplate {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/Multisite/Settings Folder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{4C82B6DD-FE7C-4144-BCB3-F21B4080568F}", "NtQ86eBk/GoIslX9bh2NcF/AH/U=", "Sitecore.Foundation.Multisite")]
    public partial interface ISettingsFolderItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/Multisite/_Site template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{BB85C5C2-9F87-48CE-8012-AF67CF4F765D}", "FqkCrixETxJ6jfZsRk9lQH6RPMk=", "Sitecore.Foundation.Multisite")]
    public partial interface I_SiteItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Host Name field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("hostname")]
        Synthesis.FieldTypes.Interfaces.ITextField HostName {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/Multisite/_SiteSettings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{BCCFEBEA-DCCB-48FE-9570-6503829EC03F}", "HIhdHwhNX9ElCoHwBb70eTvtRhQ=", "Sitecore.Foundation.Multisite")]
    public partial interface I_SiteSettingsItem : Synthesis.IStandardTemplateItem {
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Foundation.Multisite.Models.Concrete.Foundation.Multisite {
    
    
    /// <summary>Represents the /sitecore/templates/Foundation/Multisite/Datasource Configuration template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class DatasourceConfiguration : global::Synthesis.StandardTemplateItem, global::Sitecore.Foundation.Multisite.Models.Foundation.Multisite.IDatasourceConfigurationItem {
        
        private Synthesis.FieldTypes.TextField _datasourceLocation;
        
        private Synthesis.FieldTypes.PathItemReferenceField _datasourceTemplate;
        
        public DatasourceConfiguration(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public DatasourceConfiguration(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Datasource Configuration";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{C82DC5FF-09EF-4403-96D3-3CAF377B8C5B}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the DatasourceLocation field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("datasourcelocation")]
        public Synthesis.FieldTypes.Interfaces.ITextField DatasourceLocation {
            get {
                if (_datasourceLocation == null) {
                    _datasourceLocation = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{5FE1CC43-F86C-459C-A379-CD75950D85AF}"], "/sitecore/templates/Foundation/Multisite/Datasource Configuration", "DatasourceLocation"), this.GetSearchFieldValue("datasourcelocation"));
                }
                return _datasourceLocation;
            }
        }
        
        /// <summary>Represents the DatasourceTemplate field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("datasourcetemplate")]
        public Synthesis.FieldTypes.Interfaces.IPathItemReferenceField DatasourceTemplate {
            get {
                if (_datasourceTemplate == null) {
                    _datasourceTemplate = new Synthesis.FieldTypes.PathItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{498DD5B6-7DAE-44A7-9213-1D32596AD14F}"], "/sitecore/templates/Foundation/Multisite/Datasource Configuration", "DatasourceTemplate"), this.GetSearchFieldValue("datasourcetemplate"));
                }
                return _datasourceTemplate;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class DatasourceConfigurationInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{C82DC5FF-09EF-4403-96D3-3CAF377B8C5B}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new DatasourceConfiguration(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new DatasourceConfiguration(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/Multisite/Settings Folder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class SettingsFolder : global::Synthesis.StandardTemplateItem, global::Sitecore.Foundation.Multisite.Models.Foundation.Multisite.ISettingsFolderItem {
        
        public SettingsFolder(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public SettingsFolder(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Settings Folder";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{4C82B6DD-FE7C-4144-BCB3-F21B4080568F}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class SettingsFolderInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{4C82B6DD-FE7C-4144-BCB3-F21B4080568F}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new SettingsFolder(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new SettingsFolder(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/Multisite/_Site template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class _Site : global::Synthesis.StandardTemplateItem, global::Sitecore.Foundation.Multisite.Models.Foundation.Multisite.I_SiteItem {
        
        private Synthesis.FieldTypes.TextField _hostName;
        
        public _Site(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public _Site(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "_Site";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{BB85C5C2-9F87-48CE-8012-AF67CF4F765D}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Host Name field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("hostname")]
        public Synthesis.FieldTypes.Interfaces.ITextField HostName {
            get {
                if (_hostName == null) {
                    _hostName = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{B8027200-AAB0-4876-B454-DBB85ADD9E3C}"], "/sitecore/templates/Foundation/Multisite/_Site", "HostName"), this.GetSearchFieldValue("hostname"));
                }
                return _hostName;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class _SiteInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{BB85C5C2-9F87-48CE-8012-AF67CF4F765D}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new _Site(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new _Site(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/Multisite/_SiteSettings template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class _SiteSettings : global::Synthesis.StandardTemplateItem, global::Sitecore.Foundation.Multisite.Models.Foundation.Multisite.I_SiteSettingsItem {
        
        public _SiteSettings(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public _SiteSettings(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "_SiteSettings";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{BCCFEBEA-DCCB-48FE-9570-6503829EC03F}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class _SiteSettingsInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{BCCFEBEA-DCCB-48FE-9570-6503829EC03F}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new _SiteSettings(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new _SiteSettings(searchFields);
        }
    }
}
