---
ID: "694ac505-7e1d-4954-9e76-b94a8c3ed771"
Parent: "1c87ea50-cc18-48cc-86de-592e274d0c4f"
Template: "1c87ea50-cc18-48cc-86de-592e274d0c4f"
Path: /sitecore/templates/Foundation/Assets/Theme/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{1C87EA50-CC18-48CC-86DE-592E274D0C4F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161212T014715Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
