---
ID: b425067e-adb3-4a15-b565-916d4722626f
Parent: 5f1296de-1df8-4ce7-8f5a-fafc086a8efc
Template: e269fbb5-3750-427a-9149-7aa950b49301
Path: /sitecore/templates/Feature/Events/_EventSettings/Event Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160130T113030Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\admin
