---
ID: c425b1aa-48b4-4ef1-86b3-19b95acceee1
Parent: 2f75c8af-35fc-4a88-b585-7595203f442c
Template: 2f75c8af-35fc-4a88-b585-7595203f442c
Path: /sitecore/templates/Feature/News/_NewsArticle/__Standard Values
SharedFields:
- ID: c464d2d7-3382-428a-bcdf-0963c60ba0e3
  # NewsDate
  Value: $now
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 3437eaac-6ee8-460b-a33d-da1f714b5a93
      # NewsImage
      Value: "<image mediaid=\"{88032F9C-B464-44CB-B76D-513D60B9C127}\" />"
