---
ID: 78fc406f-fb34-42da-8f10-b955fe9f5a4e
Parent: 6c3b2801-5573-40cf-87ad-a2cb94fce40e
Template: 0437fee2-44c9-46a6-abe9-28858d9fee8c
Path: /sitecore/templates/Habitat/Project/Website/Parameters
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150921T023240Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
