---
ID: "068a2caa-6b59-405f-9eaf-bedb00d50f16"
Parent: "edbc9b84-815d-423b-a79f-6c5105f9edc2"
Template: "edbc9b84-815d-423b-a79f-6c5105f9edc2"
Path: /sitecore/templates/Feature/Sitemap/Pre Built Examples/Sitemap Configuration/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160518T142758Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
