---
ID: "3cac7f64-3a6e-4933-b342-26df789d3c77"
Parent: "ddbbf170-cfbd-439f-958c-a090bdf66d94"
Template: "ddbbf170-cfbd-439f-958c-a090bdf66d94"
Path: /sitecore/templates/Project/Common/Content Types/Teasers/Video Teaser/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160530T132038Z
