// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Sitecore.Feature.Accounts.Specflow
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class EditUserProfileFeature : Xunit.IClassFixture<EditUserProfileFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Edit user profile.feature"
#line hidden
        
        public EditUserProfileFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Edit user profile", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(EditUserProfileFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Edit user profile")]
        [Xunit.TraitAttribute("Description", "Account_Edit user profile_UC1_Open Edit Profile page")]
        [Xunit.TraitAttribute("Category", "NeedImplementation")]
        public virtual void Account_EditUserProfile_UC1_OpenEditProfilePage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Edit user profile_UC1_Open Edit Profile page", new string[] {
                        "NeedImplementation"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "ConfirmPassword"});
            table1.AddRow(new string[] {
                        "kov10@sitecore.net",
                        "k",
                        "k"});
#line 6
 testRunner.Given("User with following data is registered in Habitat", ((string)(null)), table1, "Given ");
#line 9
 testRunner.When("Actor moves cursor over the User icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
 testRunner.And("User clicks Edit Profile from drop-down menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.Then("EDITPROFILE title presents on page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
 testRunner.And("Page URL ends on /Edit Profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Edit user profile")]
        [Xunit.TraitAttribute("Description", "Account_Edit user profile_UC2_Update all fields_First time")]
        [Xunit.TraitAttribute("Category", "InDesign")]
        public virtual void Account_EditUserProfile_UC2_UpdateAllFields_FirstTime()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Edit user profile_UC2_Update all fields_First time", new string[] {
                        "InDesign"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "ConfirmPassword"});
            table2.AddRow(new string[] {
                        "kov10@sitecore.net",
                        "k",
                        "k"});
#line 18
 testRunner.Given("User with following data is registered in Habitat", ((string)(null)), table2, "Given ");
#line 21
 testRunner.And("Habitat website is opened on Edit Profile page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number"});
            table3.AddRow(new string[] {
                        "Teltov",
                        "Konstantin",
                        "+38(067)3333333"});
#line 22
 testRunner.When("User inputs data in to the fields", ((string)(null)), table3, "When ");
#line 25
 testRunner.And("User selects <Swiming> from Interests drop-down list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("User clicks Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And("User opens Sitecore by Admin user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.And("User opens User Manager", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.And("User clicks on <kov@sitecore.net> in user names list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("User presses Edit button on the ribbon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.And("User selects Profile tab on Edit User popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number",
                        "Interests"});
            table4.AddRow(new string[] {
                        "Teltov",
                        "Konstantin",
                        "+38(067)3333333",
                        "Swiming"});
#line 32
 testRunner.Then("Following User info presents", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Edit user profile")]
        [Xunit.TraitAttribute("Description", "Account_Edit user profile_UC3_Update all fields_Change user info")]
        [Xunit.TraitAttribute("Category", "InDesign")]
        public virtual void Account_EditUserProfile_UC3_UpdateAllFields_ChangeUserInfo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Edit user profile_UC3_Update all fields_Change user info", new string[] {
                        "InDesign"});
#line 37
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number",
                        "Interests"});
            table5.AddRow(new string[] {
                        "Teltov",
                        "Konstantin",
                        "+38(067)3333333",
                        "Swiming"});
#line 38
 testRunner.Given("Habitat user was created and updated with following info", ((string)(null)), table5, "Given ");
#line 41
 testRunner.And("Habitat website is opened on Edit Profile page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number"});
            table6.AddRow(new string[] {
                        "Maximov",
                        "Stas",
                        "+38(067)8888888"});
#line 42
 testRunner.When("User inputs data in to the fields", ((string)(null)), table6, "When ");
#line 45
 testRunner.And("User selects <Skiing> from Interests drop-down list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
 testRunner.And("User clicks Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
 testRunner.And("User opens Sitecore by Admin user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.And("User opens User Manager", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
 testRunner.And("User clicks on <kov@sitecore.net> in user names list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
 testRunner.And("User presses Edit button on the ribbon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.And("User selects Profile tab on Edit User popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number",
                        "Interests"});
            table7.AddRow(new string[] {
                        "Maximov",
                        "Stas",
                        "+38(067)8888888",
                        "Skiing"});
#line 52
 testRunner.Then("Following User info presents", ((string)(null)), table7, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Edit user profile")]
        [Xunit.TraitAttribute("Description", "Account_Edit user profile_UC4_Update one of the fields_First time")]
        [Xunit.TraitAttribute("Category", "InDesign")]
        public virtual void Account_EditUserProfile_UC4_UpdateOneOfTheFields_FirstTime()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Edit user profile_UC4_Update one of the fields_First time", new string[] {
                        "InDesign"});
#line 58
this.ScenarioSetup(scenarioInfo);
#line 59
 testRunner.Given("Habitat website is opened on Edit Profile page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name"});
            table8.AddRow(new string[] {
                        "Teltov"});
#line 60
 testRunner.When("User inputs data in to the fields", ((string)(null)), table8, "When ");
#line 63
 testRunner.And("User clicks Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
 testRunner.And("User opens Sitecore by Admin user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
 testRunner.And("User opens User Manager", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
 testRunner.And("User clicks on <kov@sitecore.net> in user names list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 67
 testRunner.And("User presses Edit button on the ribbon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 68
 testRunner.And("User selects Profile tab on Edit User popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name"});
            table9.AddRow(new string[] {
                        "Teltov"});
#line 69
 testRunner.Then("Following User info presents", ((string)(null)), table9, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "First Name",
                        "Phone number",
                        "Interests"});
            table10.AddRow(new string[] {
                        "empty",
                        "empty",
                        "empty"});
#line 72
  testRunner.And("Following user info absents", ((string)(null)), table10, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Edit user profile")]
        [Xunit.TraitAttribute("Description", "Account_Edit user profile_UC5_Update one of the fields_Change user info")]
        [Xunit.TraitAttribute("Category", "InDesign")]
        public virtual void Account_EditUserProfile_UC5_UpdateOneOfTheFields_ChangeUserInfo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Edit user profile_UC5_Update one of the fields_Change user info", new string[] {
                        "InDesign"});
#line 78
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number",
                        "Interests"});
            table11.AddRow(new string[] {
                        "Teltov",
                        "Konstantin",
                        "+38(067)3333333",
                        "Swiming"});
#line 79
 testRunner.Given("Habitat user was created and updated with following info", ((string)(null)), table11, "Given ");
#line 82
 testRunner.And("Habitat website is opened on Edit Profile page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name"});
            table12.AddRow(new string[] {
                        "Maximov"});
#line 83
 testRunner.When("User inputs data in to the fields", ((string)(null)), table12, "When ");
#line 86
 testRunner.And("User clicks Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
 testRunner.And("User opens Sitecore by Admin user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
 testRunner.And("User opens User Manager", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 89
 testRunner.And("User clicks on <kov@sitecore.net> in user names list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
 testRunner.And("User presses Edit button on the ribbon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 91
 testRunner.And("User selects Profile tab on Edit User popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Last Name",
                        "First Name",
                        "Phone number",
                        "Interests"});
            table13.AddRow(new string[] {
                        "Maximov",
                        "Konstantin",
                        "+38(067)3333333",
                        "Swiming"});
#line 92
 testRunner.Then("Following User info presents", ((string)(null)), table13, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Edit user profile")]
        [Xunit.TraitAttribute("Description", "Account_Edit user profile_UC6_Phone validation_Two plus symbols in the begining")]
        [Xunit.TraitAttribute("Category", "InDesign")]
        public virtual void Account_EditUserProfile_UC6_PhoneValidation_TwoPlusSymbolsInTheBegining()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Edit user profile_UC6_Phone validation_Two plus symbols in the begining", new string[] {
                        "InDesign"});
#line 98
this.ScenarioSetup(scenarioInfo);
#line 99
 testRunner.Given("Habitat website is opened on Edit Profile page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number"});
            table14.AddRow(new string[] {
                        "++380673333333"});
#line 100
 testRunner.When("User inputs data in to the fields", ((string)(null)), table14, "When ");
#line 103
 testRunner.And("User clicks Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Error message"});
            table15.AddRow(new string[] {
                        "Phone number should contain only +, ( ) and digits"});
#line 104
 testRunner.Then("System shows following error message for the Edit Profile", ((string)(null)), table15, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Edit user profile")]
        [Xunit.TraitAttribute("Description", "Account_Edit user profile_UC6_Phone validation_Brackets without number")]
        [Xunit.TraitAttribute("Category", "InDesign")]
        public virtual void Account_EditUserProfile_UC6_PhoneValidation_BracketsWithoutNumber()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Edit user profile_UC6_Phone validation_Brackets without number", new string[] {
                        "InDesign"});
#line 109
this.ScenarioSetup(scenarioInfo);
#line 110
 testRunner.Given("Habitat website is opened on Edit Profile page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number"});
            table16.AddRow(new string[] {
                        "+()380673333333"});
#line 111
 testRunner.When("User inputs data in to the fields", ((string)(null)), table16, "When ");
#line 114
 testRunner.And("User clicks Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Error message"});
            table17.AddRow(new string[] {
                        "Phone number should contain only +, ( ) and digits"});
#line 115
 testRunner.Then("System shows following error message for the Edit Profile", ((string)(null)), table17, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Edit user profile")]
        [Xunit.TraitAttribute("Description", "Account_Edit user profile_UC6_Phone validation_Digits in phone field")]
        [Xunit.TraitAttribute("Category", "InDesign")]
        public virtual void Account_EditUserProfile_UC6_PhoneValidation_DigitsInPhoneField()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Edit user profile_UC6_Phone validation_Digits in phone field", new string[] {
                        "InDesign"});
#line 121
this.ScenarioSetup(scenarioInfo);
#line 122
 testRunner.Given("Habitat website is opened on Edit Profile page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number"});
            table18.AddRow(new string[] {
                        "+38067Kostia"});
#line 123
 testRunner.When("User inputs data in to the fields", ((string)(null)), table18, "When ");
#line 126
 testRunner.And("User clicks Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Error message"});
            table19.AddRow(new string[] {
                        "Phone number should contain only +, ( ) and digits"});
#line 127
 testRunner.Then("System shows following error message for the Edit Profile", ((string)(null)), table19, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Edit user profile")]
        [Xunit.TraitAttribute("Description", "Account_Edit user profile_UC6_Phone validation_Phone number lenght should be less" +
            " than 20")]
        [Xunit.TraitAttribute("Category", "InDesign")]
        public virtual void Account_EditUserProfile_UC6_PhoneValidation_PhoneNumberLenghtShouldBeLessThan20()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Edit user profile_UC6_Phone validation_Phone number lenght should be less" +
                    " than 20", new string[] {
                        "InDesign"});
#line 133
this.ScenarioSetup(scenarioInfo);
#line 134
 testRunner.Given("Habitat website is opened on Edit Profile page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number"});
            table20.AddRow(new string[] {
                        "+38067333333333333331"});
#line 135
 testRunner.When("User inputs data in to the fields", ((string)(null)), table20, "When ");
#line 138
 testRunner.And("User clicks Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Error message"});
            table21.AddRow(new string[] {
                        "Phone number lenght should be less than 20"});
#line 139
 testRunner.Then("System shows following error message for the Edit Profile", ((string)(null)), table21, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Edit user profile")]
        [Xunit.TraitAttribute("Description", "Account_Edit user profile_UC7_Empty user profile is saved")]
        [Xunit.TraitAttribute("Category", "InDesign")]
        public virtual void Account_EditUserProfile_UC7_EmptyUserProfileIsSaved()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account_Edit user profile_UC7_Empty user profile is saved", new string[] {
                        "InDesign"});
#line 145
this.ScenarioSetup(scenarioInfo);
#line 146
 testRunner.Given("Habitat website is opened on Edit Profile page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 147
 testRunner.When("User clicks Save button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 148
 testRunner.And("User opens Sitecore by Admin user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 149
 testRunner.And("User opens User Manager", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 150
 testRunner.And("User clicks on <kov@sitecore.net> in user names list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 151
 testRunner.And("User presses Edit button on the ribbon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 152
 testRunner.And("User selects Profile tab on Edit User popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 153
 testRunner.Then("No any user profile fields present", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                EditUserProfileFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                EditUserProfileFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
