---
ID: 0a94847b-b324-4d23-af51-94b0bc073f5f
Parent: 89d988bc-a9a7-43f5-a9fd-a05b0b164720
Template: 89d988bc-a9a7-43f5-a9fd-a05b0b164720
Path: /sitecore/templates/Feature/Social/_TwitterFeed/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 099e4085-150c-4073-88d9-8b159d9a8b01
      # FeedTitle
      Value: Tweets by @$name
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20151123T160017Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: 92ef8986-45e2-42de-913f-b91fd960297a
      # TwitterUrl
      Value: "<link linktype=\"external\" url=\"https://twitter.com/$name\" />"
