---
ID: "ff12fa13-d8e7-4806-8251-d7819b7aae5a"
Parent: "fec0e62a-01fd-40e5-88f3-e5229fe79527"
Template: "fec0e62a-01fd-40e5-88f3-e5229fe79527"
Path: /sitecore/templates/Feature/Teasers/_TeaserContent/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160322T023514Z
